### ISSUE TITLE
Change colors of the website

### ISSUE THREAD

**Issue by ch1kim0n1** [ch1kim0n1/100DayChallenge_ch1kim0n1.github.io#2]

**Comment by ch1kim0n1** [comment]
Need to work on colors of the website

**Comment by stepan323446** [comment]
Изменить пару стилей в style.css и всё. Там не так уж и много строчек кода

**Comment by ch1kim0n1** [comment]
@stepan323446 Я знаю, я даже нашёл цвета которые хочу изменить, но я хочу подобрать те цвета которые будут хорошо сочетаться с кнопками и не будет похож на Anilist.

**Comment by stepan323446** [comment]
Интересно, мы единственные, кто заморачиваются так с челледжем? :)
